# Generated by Django 4.2.4 on 2023-09-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_contact_subject_blogs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='category',
        ),
        migrations.AlterField(
            model_name='blogs',
            name='author',
            field=models.CharField(max_length=20),
        ),
    ]
